version: "3"
services:

  service_example:
    image: fidelissauro/chip:v1
    ports:
      - "8001:8000"
    networks:
      - developer

  service_example_fail:
    image: fidelissauro/chip:v2-error
    ports:
      - "8002:8000"
    networks:
      - developer

  envoy_proxy:
    build: .
    ports:
      - "8080:8080"
    networks:
      - developer

networks:
  developer:
